version: "3.9"

services:
  db:
    image: mongo:latest
    container_name: todo-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  server:
    build: ./server
    container_name: todo-backend
    image: todo-backend
    restart: always
    ports:
      - "4000:5000"
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://db:27017/todoapp
      - NODE_ENV=production
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - db

  client:
    build:
      context: ./client
      args:
        REACT_APP_SERVERURL: http://localhost:4000  # backend URL
    container_name: todo-frontend
    image: todo-frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - server

volumes:
  mongo-data: